# Site settings
title: Dot Eight
email: contact@dot-eight.com
description: "Dot Eight"
url: "http://www.dot-eight.com"
twitter_username: dot-eight
github_username:  dot-eight

# Build settings
markdown: kramdown
highlighter:      pygments
permalink:        pretty
